name: sftest-rw
version: v1 
type: instance-secret 
description: "read and write intance-secret for snowflake depot" 
layer: user 
instance-secret:
  type: key-value-properties 
  acl: rw
  data:
    username: 
    password: 