name: sftest-r 
version: v1 
type: instance-secret 
description: "read intance-secret for snowflake depot" 
layer: user 
instance-secret:
  type: key-value-properties 
  acl: r 
  data:
    username: 
    password: 