name: product-affinity-api
version: v1
type: service
tags:
  - service
  - dataos:type:resource
  - dataos:resource:service
  - dataos:layer:user
description: Talos Service
workspace: public
service:
  servicePort: 3000
  ingress:
    enabled: true
    stripPath: true
    path: /talos/public:product-affinity-api
    noAuthentication: true
  replicas: 1
  logLevel: DEBUG
  compute: runnable-default
  envs:
    TALOS_SCHEMA_PATH: product-affinity-training/activation/data-apis
    TALOS_BASE_PATH: /talos/public:product-affinity-api
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  stack: talos:2.0
  dataosSecrets:
    - name: bitbucket-cred
      allKeys: true
  stackSpec:
    repo:
      url: https://bitbucket.org/tmdc/product-affinity-training
      projectDirectory: product-affinity-training/activation/data-apis
      syncFlags:
        - --ref=main